import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar";
import Footer from "@/components/footer"; // ✅ Import Footer
import LayoutWithBackground from "@/components/LayoutWithBackground"; // ✅ Background wrapper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutWithBackground>
          <Navbar />
          <div className="relative z-10">
            {children}
            <Footer /> {/* ✅ Footer placed right after all page content */}
          </div>
        </LayoutWithBackground>
      </body>
    </html>
  );
}
